# Practice - 1
---
Date: 20/11/2023 Mon

The `reduce()`

In [3]:
from fractions import Fraction
from functools import reduce

def product(fracs):
    t = reduce(lambda x,y: x*y, fracs)
    return t.numerator, t.denominator

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)

5 8


# numpy 

In [6]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy
numpy.set_printoptions(legacy='1.13')

n, m = [int(x.strip()) for x in input().split()]

print(numpy.eye(n, m))



[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Enter multiple inputs

In [2]:
from collections import Counter

x = list(map(int, input().split()))

shoes = Counter(x)

In [4]:
print(shoes)

Counter({1: 4, 2: 2, 3: 1, 4: 1, 5: 1})


In [7]:
from itertools import permutations # arangement

nums = list(map(int, input().split()))

p = list(permutations(nums))

In [8]:
p

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]

In [11]:
from itertools import combinations # selection

nums = list(map(int, input("list:").split()))
select = int(input("select: "))
s = list(combinations(nums, select))
print(s)

[(1,), (2,), (3,), (4,), (5,)]


In [28]:
from itertools import combinations
# Enter your code here. Read input from STDIN. Print output to STDOUT
string, k = input().split()[:2]
k = int(k)

possible_combinations = []

for i in range(k):
    possible_combinations.extend(list(combinations(string, i+1)))

# sort the combinations by alphabetical order and size
possible_combinations.sort(key=lambda x: (len(x), sorted(x)))

for x in possible_combinations:
    print(''.join(sorted(x)))

A
C
H
K
AC
AH
AK
CH
CK
HK
